# Generated by Django 5.2.8 on 2025-11-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcardapio',
            name='disponivel',
            field=models.BooleanField(default=True, help_text='Item disponível para pedidos'),
        ),
        migrations.AddField(
            model_name='itemcardapio',
            name='quantidade_estoque',
            field=models.IntegerField(default=0, help_text='Quantidade disponível em estoque'),
        ),
    ]
