# Generated by Django 5.2.8 on 2025-11-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_itemcardapio_disponivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observações ou pedidos especiais (ex: sem cebola)'),
        ),
    ]
