# Generated by Django 5.2.8 on 2026-06-10 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedido_dt_pedido_to_datetime'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itempedido',
            name='pedido_produto_unico_por_pedido_e_item',
        ),
    ]
